logging:
  level:
    root: INFO

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger
    csrf:
      enabled: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"

