spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/steam_prices
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS}  %-5level [%thread] %-50logger{50} : %msg%n"

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

server:
  error:
    whitelabel:
      enabled: false
