spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/steam_price_tracker
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  mvc:
    problemdetails:
      enabled: true
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    enabled-by-default: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS}  %-5level [%thread] %-50logger{50} : %msg%n"

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

server:
  error:
    whitelabel:
      enabled: false

google:
  captcha:
    enabled: true
    secret-key: ${CAPTCHA_SECRET_KEY}

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
