spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/steam_price_tracker
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  mvc:
    problemdetails:
      enabled: true
  threads:
    virtual:
      enabled: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

management:
  endpoints:
    enabled-by-default: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS}  %-5level [%thread] %-50logger{50} : %msg%n"

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

cors:
  allowed-origins: "http://localhost:3000"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"
  allowed-credentials: true

server:
  error:
    whitelabel:
      enabled: false
