logging:
  level:
    root: INFO

spring:
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger
    csrf:
      enabled: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"

