spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/steam_prices
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root

    testWhileIdle: true
    test-on-borrow: true
    hikari:
      connection-test-query: SELECT 1
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      validationTimeout: 300000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  mvc:
    problemdetails:
      enabled: true
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    enabled-by-default: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS}  %-5level [%thread] %-50logger{50} : %msg%n"

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

cors:
  allowed-origins: "http://localhost:3000"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"
  allowed-credentials: true

server:
  error:
    whitelabel:
      enabled: false
